Hotstring(":*:ram.",			func("ViaClipboard").bind("Reliability, Availability, Maintainability"), "On")
Hotstring(":B0:ram", func("NormalWay").bind("{Backspace 4}RAM"), "On")
Hotstring(":*:rams.",			func("ViaClipboard").bind("Reliability, Availability, Maintainability and Safety"), "On")
Hotstring(":B0:rams", func("NormalWay").bind("{Backspace 5}RAMS"), "On")
Hotstring(":*:qrams.",			func("ViaClipboard").bind("Quality, Reliability, Availability, Maintainability, Safety"), "On")
Hotstring(":B0:qrams", func("NormalWay").bind("{Backspace 6}QRAMS"), "On")
Hotstring(":*:mdt.",			func("ViaClipboard").bind("Mean Down Time"), "On")
Hotstring(":B0:mdt", func("NormalWay").bind("{Backspace 4}MDT"), "On")
Hotstring(":*:mtbf.",			func("ViaClipboard").bind("Mean Time Between Failures"), "On")
Hotstring(":B0:mtbf", func("NormalWay").bind("{Backspace 5}MTBF"), "On")
Hotstring(":*:mttr.",			func("ViaClipboard").bind("Mean Time To Restore"), "On")
Hotstring(":B0:mttr", func("NormalWay").bind("{Backspace 5}MTTR"), "On")
Hotstring(":*:mtbm.",			func("ViaClipboard").bind("Mean Time Between Maintainances"), "On")
Hotstring(":B0:mtbm", func("NormalWay").bind("{Backspace 5}MTBM"), "On")
Hotstring(":*:mttf.",			func("ViaClipboard").bind("Mean Time To Failure"), "On")
Hotstring(":B0:mttf", func("NormalWay").bind("{Backspace 5}MTTF"), "On")
Hotstring(":*:mut.",			func("ViaClipboard").bind("Mean Up Time"), "On")
Hotstring(":B0:mut", func("NormalWay").bind("{Backspace 4}MUT"), "On")
Hotstring(":*:sil.",			func("ViaClipboard").bind("Safety Integrity Level"), "On")
Hotstring(":B0:sil", func("NormalWay").bind("{Backspace 4}SIL"), "On")
Hotstring(":*:pcb.",			func("ViaClipboard").bind("Printed Circuit Board"), "On")
Hotstring(":B0:pcb", func("NormalWay").bind("{Backspace 4}PCB"), "On")
Hotstring(":*:ups.",			func("ViaClipboard").bind("Uninterruptable Power Supply"), "On")
Hotstring(":B0:ups", func("NormalWay").bind("{Backspace 4}UPS"), "On")
Hotstring(":*:usb.",			func("ViaClipboard").bind("Universal Serial Bus"), "On")
Hotstring(":B0:usb", func("NormalWay").bind("{Backspace 4}USB"), "On")
Hotstring(":*:iris.",			func("ViaClipboard").bind("International Railway Industry Standard for the evaluation of railway management systems"), "On")
Hotstring(":B0:iris", func("NormalWay").bind("{Backspace 5}IRIS"), "On")
Hotstring(":*:tsi.",			func("ViaClipboard").bind("Technical Specifications for Interoperability"), "On")
Hotstring(":B0:tsi", func("NormalWay").bind("{Backspace 4}TSI"), "On")
Hotstring(":*:faq.",			func("ViaClipboard").bind("Frequently Asked Questions"), "On")
Hotstring(":B0:faq", func("NormalWay").bind("{Backspace 4}FAQ"), "On")
Hotstring(":*:ahk.",			func("ViaClipboard").bind("AutoHotkey"), "On")
Hotstring(":B0:ahk", func("NormalWay").bind("{Backspace 4}AHK"), "On")
Hotstring(":*:vba.",			func("ViaClipboard").bind("Visual Basic for Applications"), "On")
Hotstring(":B0:vba", func("NormalWay").bind("{Backspace 4}VBA"), "On")
Hotstring(":*:hdmi.",			func("ViaClipboard").bind("High-Definition Multimedia Interface"), "On")
Hotstring(":B0:hdmi", func("NormalWay").bind("{Backspace 5}HDMI"), "On")
Hotstring(":*:emc.",			func("ViaClipboard").bind("Electro-Magnetic Compatibility"), "On")
Hotstring(":B0:emc", func("NormalWay").bind("{Backspace 4}EMC"), "On")
Hotstring(":*:hart.",			func("ViaClipboard").bind("Highway Addressable Remote Transducer Protocol"), "On")
Hotstring(":B0:hart", func("NormalWay").bind("{Backspace 5}HART"), "On")
Hotstring(":*:erp.",			func("ViaClipboard").bind("Enterprise Resource Planning"), "On")
Hotstring(":B0:erp", func("NormalWay").bind("{Backspace 4}ERP"), "On")
Hotstring(":*:c2ms.",			func("ViaClipboard").bind("Component Content Management System"), "On")
Hotstring(":B0:c2ms", func("NormalWay").bind("{Backspace 5}CCMS"), "On")
Hotstring(":*:lc2.",			func("ViaClipboard").bind("Life Cycle Cost"), "On")
Hotstring(":B0:lc2", func("NormalWay").bind("{Backspace 4}LLC"), "On")
Hotstring(":*:ceo.",			func("ViaClipboard").bind("Chief Executive Officer"), "On")
Hotstring(":B0:ceo", func("NormalWay").bind("{Backspace 4}CEO"), "On")
Hotstring(":*:hds.",			func("ViaClipboard").bind("Hardware Design Specification"), "On")
Hotstring(":B0:hds", func("NormalWay").bind("{Backspace 4}HDS"), "On")
Hotstring(":*:has.",			func("ViaClipboard").bind("Hardware Architecture Specification"), "On")
Hotstring(":B0:has", func("NormalWay").bind("{Backspace 4}HAS"), "Off")
Hotstring(":*:kpi.",			func("ViaClipboard").bind("Key Performance Indicator"), "On")
Hotstring(":B0:kpi", func("NormalWay").bind("{Backspace 4}KPI"), "On")
Hotstring(":*:gui.",			func("ViaClipboard").bind("Graphical User Interface"), "On")
Hotstring(":B0:gui", func("NormalWay").bind("{Backspace 4}GUI"), "On")
Hotstring(":*:etcs.", func("NormalWay").bind("European Train Control System"), "On")
Hotstring(":B0:etcs", func("NormalWay").bind("{Backspace 5}ETCS"), "On")
Hotstring(":*:ertms.",			func("ViaClipboard").bind("European Rail Traffic Management System"), "On")
Hotstring(":B0:ertms", func("NormalWay").bind("{Backspace 6}ERTMS"), "On")
Hotstring(":*:era.",			func("ViaClipboard").bind("European Railway Agency"), "On")
Hotstring(":B0:era", func("NormalWay").bind("{Backspace 4}ERA"), "On")
Hotstring(":*:fai.",			func("ViaClipboard").bind("First Article Inspection"), "On")
Hotstring(":B0:fai", func("NormalWay").bind("{Backspace 4}FAI"), "On")
Hotstring(":*:thr.",			func("ViaClipboard").bind("Tolerable Hazard Rate"), "On")
Hotstring(":B0:thr", func("NormalWay").bind("{Backspace 4}THR"), "On")
Hotstring(":*:dita.",			func("ViaClipboard").bind("Darwin Information Typing Architecture"), "On")
Hotstring(":B0:dita", func("NormalWay").bind("{Backspace 5}DITA"), "On")
Hotstring(":*:bom.",			func("ViaClipboard").bind("Bill of Materials"), "On")
Hotstring(":B0:bom", func("NormalWay").bind("{Backspace 4}BOM"), "On")
Hotstring(":*:ip.",				func("ViaClipboard").bind("IP Code, Ingress Protection code (https://en.wikipedia.org/wiki/IP_Code	)"), "On")
Hotstring(":B0:ip", func("NormalWay").bind("{Backspace 3}IP"), "On")
Hotstring(":*:lop.",			func("ViaClipboard").bind("List of Open Points"), "On")
Hotstring(":B0:lop", func("NormalWay").bind("{Backspace 4}LoP"), "On")
Hotstring(":*:srac.",			func("ViaClipboard").bind("Safety Related Application Condition"), "On")
Hotstring(":B0:srac", func("NormalWay").bind("{Backspace 5}SRAC"), "On")
Hotstring(":*:ga.", func("ViaClipboard").bind("Generic Application"), "On")
Hotstring(":B0*:ga", func("NormalWay").bind("{Backspace 2}GA"), "Off")
Hotstring(":*:sa.",				func("ViaClipboard").bind("Specific Application"), "On")
Hotstring(":B0:sa", func("NormalWay").bind("{Backspace 3}SA"), "On")
Hotstring(":*:fat.",			func("ViaClipboard").bind("Factory Acceptance Test"), "On")
Hotstring(":B0:fat", func("NormalWay").bind("{Backspace 4}FAT"), "On")
Hotstring(":*:nda.",			func("ViaClipboard").bind("Non-Disclosure Agreement"), "On")
Hotstring(":B0:nda", func("NormalWay").bind("{Backspace 4}NDA"), "On")
Hotstring(":*:sla.",			func("ViaClipboard").bind("Service-Level Agreement"), "On")
Hotstring(":B0:sla", func("NormalWay").bind("{Backspace 4}SLA"), "On")
Hotstring(":*:tffr.",			func("ViaClipboard").bind("Tolerable Functional Failure Rate"), "On")
Hotstring(":B0:tffr", func("NormalWay").bind("{Backspace 5}TFFR"), "On")
Hotstring(":*:cop.",			func("ViaClipboard").bind("Code of Practice"), "On")
Hotstring(":B0:cop", func("NormalWay").bind("{Backspace 4}COP"), "Off")
Hotstring(":*:cots.",			func("ViaClipboard").bind("Commercial Off-The-Shelf"), "On")
Hotstring(":B0:cots", func("NormalWay").bind("{Backspace 5}COTS"), "On")
Hotstring(":*:emi.",			func("ViaClipboard").bind("Electromagnetic Interference"), "On")
Hotstring(":B0:emi", func("NormalWay").bind("{Backspace 4}EMI"), "On")
Hotstring(":*:fracas.",			func("ViaClipboard").bind("Failure Reporting Analysis and Corrective Action System"), "On")
Hotstring(":B0:fracas", func("NormalWay").bind("{Backspace 7}FRACAS"), "On")
Hotstring(":*:fmea.",			func("ViaClipboard").bind("Failure Mode and Effects Analysis"), "On")
Hotstring(":B0:fmea", func("NormalWay").bind("{Backspace 5}FMEA"), "On")
Hotstring(":*:fmeca.",			func("ViaClipboard").bind("Failure Mode, Effects and Criticality Analysis"), "On")
Hotstring(":B0:fmeca", func("NormalWay").bind("{Backspace 6}FMECA"), "On")
Hotstring(":*:fta.",			func("ViaClipboard").bind("Fault Tree Analysis"), "On")
Hotstring(":B0:fta", func("NormalWay").bind("{Backspace 4}FTA"), "On")
Hotstring(":*:rap.",			func("ViaClipboard").bind("Risk Acceptance Principle"), "On")
Hotstring(":B0:rap", func("NormalWay").bind("{Backspace 4}RAP"), "On")
Hotstring(":*:rac.",			func("ViaClipboard").bind("Risk Acceptance Criteria"), "On")
Hotstring(":B0:rac", func("NormalWay").bind("{Backspace 4}RAC"), "On")
Hotstring(":*:ere.",			func("ViaClipboard").bind("Explicit Risk Estimation"), "On")
Hotstring(":B0:ere", func("NormalWay").bind("{Backspace 4}ERE"), "On")
Hotstring(":*:lad.",			func("ViaClipboard").bind("Logistic and Administrative Delay"), "On")
Hotstring(":B0:lad", func("NormalWay").bind("{Backspace 4}LAD"), "On")
Hotstring(":*:vat.",			func("ViaClipboard").bind("Value Added Tax"), "On")
Hotstring(":B0:vat", func("NormalWay").bind("{Backspace 4}VAT"), "On")
Hotstring(":*:ncr.",			func("ViaClipboard").bind("Non Conformance Report"), "On")
Hotstring(":B0:ncr", func("NormalWay").bind("{Backspace 4}NCR"), "On")
Hotstring(":*:ic.",				func("ViaClipboard").bind("Interoperability Constituent"), "On")
Hotstring(":B0:ic", func("NormalWay").bind("{Backspace 3}IC"), "On")
Hotstring(":B0:ga ", func("NormalWay").bind("{Backspace 3}GA"), "On")
