Hotstring(":*:svn",				func("ViaClipboard").bind("SVN"), "On")
Hotstring(":*:sap",				func("ViaClipboard").bind("SAP"), "On")
Hotstring(":*:easm.",			func("ViaClipboard").bind("EASM"), "On")
Hotstring(":*:qnx",				func("ViaClipboard").bind("QNX"), "On")
Hotstring(":*:rs232",			func("ViaClipboard").bind("RS232"), "On")
Hotstring(":*:rs485",			func("ViaClipboard").bind("RS485"), "On")
Hotstring(":*:uic60",			func("ViaClipboard").bind("UIC60"), "On")
Hotstring(":*:s49",				func("ViaClipboard").bind("S49"), "On")
Hotstring(":*:iscala",			func("ViaClipboard").bind("iSCALA"), "On")
Hotstring(":*:ditaexchange",	func("ViaClipboard").bind("DitaExchange"), "On")
Hotstring(":*:pma",				func("ViaClipboard").bind("PMAN"), "On")
Hotstring(":*:dokt",			func("ViaClipboard").bind("DokT (Dokumentacja Techniczna)"), "On")
Hotstring(":*:dokr",			func("ViaClipboard").bind("DokR (Dokumentacja Robocza)"), "On")
Hotstring(":*:easm",			func("ViaClipboard").bind("EASM"), "On")