Hotstring(":*:rene",			func("ViaClipboard").bind("René"), "On")
Hotstring(":*:guenther",		func("ViaClipboard").bind("Günther"), "On")
Hotstring(":*:pek",				func("ViaClipboard").bind("Pék"), "On")
Hotstring(":*:stuhn",			func("ViaClipboard").bind("Stühn"), "On")
Hotstring(":*:joerg",			func("ViaClipboard").bind("Jörg"), "On")
Hotstring(":*:jorg",			func("ViaClipboard").bind("Jörg"), "On")
Hotstring(":*:soren",			func("ViaClipboard").bind("Søren"), "On")
Hotstring(":*:js.",				func("ViaClipboard").bind("Jarosław Stec"), "On")
Hotstring(":*:masz.",			func("ViaClipboard").bind("Maciej Szczepański"), "On")
Hotstring(":*:mib.",			func("ViaClipboard").bind("Michał Bigus"), "On")
Hotstring(":*:pw.",				func("ViaClipboard").bind("Przemysław Wołoszyk"), "On")
Hotstring(":*:ag.",				func("ViaClipboard").bind("Ariadna Grzona"), "On")
Hotstring(":*:gl.",				func("ViaClipboard").bind("Günther Lehner"), "On")
Hotstring(":*:rb.",				func("ViaClipboard").bind("René Berger"), "On")
Hotstring(":*:jm.",				func("ViaClipboard").bind("Jan Mironkiewicz"), "On")
Hotstring(":*:nb.",				func("ViaClipboard").bind("Natalia Budzińska"), "On")
Hotstring(":*:mo.",				func("ViaClipboard").bind("Mariusz Ossowski"), "On")
Hotstring(":*:pp.",				func("ViaClipboard").bind("Piotr Pék"), "On")
Hotstring(":*:fb.",				func("ViaClipboard").bind("Filip Bisztyga"), "On")
Hotstring(":*:sm.",				func("ViaClipboard").bind("Sebastian Meyer"), "On")
Hotstring(":*:pl.", func("ViaClipboard").bind("Przemysław Latarski"), "On")
Hotstring(":*:pk.",				func("ViaClipboard").bind("Paweł Kopacz"), "On")
Hotstring(":*:jd.",				func("ViaClipboard").bind("Joanna Damrat"), "On")
Hotstring(":*:rg.",				func("ViaClipboard").bind("Rafał Golicki"), "On")
Hotstring(":*:kw.",				func("ViaClipboard").bind("Kamil Wilkanowski"), "On")
Hotstring(":*:mg.",				func("ViaClipboard").bind("Michalina Gołąbek"), "On")
Hotstring(":*:zk.",				func("ViaClipboard").bind("Zbigniew Kosiak"), "On")
Hotstring(":*:km.",				func("ViaClipboard").bind("Krzysztof Michalak"), "On")
Hotstring(":*:ks.",				func("ViaClipboard").bind("Krystian Stasiński"), "On")
Hotstring(":*:tw.",				func("ViaClipboard").bind("Trąbki Wielkie"), "On")
Hotstring(":*:aw.",				func("ViaClipboard").bind("Agata Wilary"), "On")
Hotstring(":*:mn.",				func("ViaClipboard").bind("Marta Nibus"), "On")
Hotstring(":*:je.",				func("ViaClipboard").bind("Jörg Engers"), "On")
Hotstring(":*:jam.",			func("ViaClipboard").bind("Jakub Masiak"), "On")
