Hotstring(":*:tuv.",		func("ViaClipboard").bind("German: Technischer Überwachungsverein, English: Technical Inspection Association ` "), "On")
Hotstring("::tuv", func("ViaClipboard").bind("TÜV"), "On")
Hotstring("::sud",			func("ViaClipboard").bind("SÜD"), "On")
Hotstring(":*:gmbh.",		func("ViaClipboard").bind("German: Gesellschaft mit beschränkter Haftung, English: company with limited liability ` "), "On")
Hotstring("::gmbh",			func("ViaClipboard").bind("GmbH ` "), "On")
Hotstring(":*:obb.",		func("ViaClipboard").bind("German: Österreichische Bundesbahnen, English: Austrian Federal Railways ` "), "On")
Hotstring("::obb",			func("ViaClipboard").bind("ÖBB ` "), "On")
Hotstring(":*:sbb.",		func("ViaClipboard").bind("German: Schweizerische Bundesbahnen, English: Swiss Federal Railways"), "On")
Hotstring("::sbb", func("ViaClipboard").bind("SBB"), "On")
