Hotstring(":*:pms", 		func("ViaClipboard").bind("Pozdrawia ms"), "On")
Hotstring(":*:m.", 			func("ViaClipboard").bind("Maciej"), "On")
Hotstring(":*:s.", 			func("ViaClipboard").bind("Słojewski"), "On")
Hotstring(":*:telms",		func("ViaClipboard").bind("+48 601 403 775"), "On")
Hotstring(":b0*:m@2",		func("NormalWay").bind("{BackSpace 17}@mslonik.pl"), "On")
Hotstring(":b0*:m@",		func("NormalWay").bind("{BackSpace 2}maciej.slojewski@voestalpine.com"), "On")
Hotstring(":*:zws",			func("ViaClipboard").bind("Z wyrazami szacunku`, Maciej Słojewski"), "On")
Hotstring(":c*:kr`t",		func("ViaClipboard").bind("Kind regards`, Maciej Słojewski"), "On")
Hotstring(":*:dw.",			func("ViaClipboard").bind("Do wiadomości.`r`n`r`nPozdrawia ms"), "On")
Hotstring(":*:v.",			func("ViaClipboard").bind("V523580"), "On")
Hotstring(":*:dd", 			func("NormalWay").bind("Dzień dobry, {Shift Down}{Enter 2}{Shift Up}"), "On")
