Hotstring("::bait",				func("ViaClipboard").bind("BAiT"), "On")
Hotstring(":*:bait.",			func("ViaClipboard").bind("Biuro Automatyki i Telekomunikacji"), "On")
Hotstring("::bhp",				func("ViaClipboard").bind("BHP"), "On")
Hotstring(":*:bhp.",			func("ViaClipboard").bind("Bezpieczeństwo i Higiena Pracy"), "On")
Hotstring(":*0:dtr", func("ViaClipboard").bind("DTR"), "On")
Hotstring(":*:dtr.",			func("ViaClipboard").bind("Dokumentacja Techniczno-Ruchowa"), "On")
Hotstring("::ersat",			func("ViaClipboard").bind("ERSAT"), "On")
Hotstring(":*:ersat.",			func("ViaClipboard").bind("Elektroniczny Rejestr Stanów Awaryjnych Taboru"), "On")
Hotstring("::ik",				func("ViaClipboard").bind("IK"), "On")
Hotstring(":*:ik.",				func("ViaClipboard").bind("Instytut Kolejnictwa"), "On")
Hotstring("::nip",				func("ViaClipboard").bind("NIP"), "On")
Hotstring(":*:nip.",			func("ViaClipboard").bind("Numer Identyfikacji Podatkowej"), "On")
Hotstring("::pesel",			func("ViaClipboard").bind("PESEL"), "On")
Hotstring(":*:pesel.",			func("ViaClipboard").bind("Powszechny Elektroniczny System Ewidencji Ludności"), "On")
Hotstring("::pkp",				func("ViaClipboard").bind("PKP"), "On")
Hotstring(":*:pkp.",			func("ViaClipboard").bind("Polskie Koleje Państwowe"), "On")
Hotstring("::plk",				func("ViaClipboard").bind("PLK"), "On")
Hotstring(":*:plk.", func("ViaClipboard").bind("Polskie Linie Kolejowe"), "On")
Hotstring("::utk",				func("ViaClipboard").bind("UTK"), "On")
Hotstring(":*:utk.",			func("ViaClipboard").bind("Urząd Transportu Kolejowego"), "On")
Hotstring(":*:srk.",			func("ViaClipboard").bind( "(urządzenia) sterowania ruchem kolejowym"), "On")
Hotstring("::wtwio",			func("ViaClipboard").bind("WTWiO"), "On")
Hotstring(":*:wtwio.",			func("ViaClipboard").bind("Warunki Techniczne Wytwarzania i Odbioru"), "On")