Hotstring(":*:polska",			func("ViaClipboard").bind("Polska"), "On")
Hotstring(":*:poland",			func("ViaClipboard").bind("Poland"), "On")
Hotstring(":*:polish",			func("ViaClipboard").bind("Polish"), "On")
Hotstring(":*:english",			func("ViaClipboard").bind("English"), "On")
Hotstring(":*:german",			func("ViaClipboard").bind("German"), "On")
Hotstring(":*:germany",			func("ViaClipboard").bind("Germany"), "On")
Hotstring(":*:a la",			func("ViaClipboard").bind("à la"), "On")
Hotstring(":*:a propos", 			func("ViaClipboard").bind("à propos"), "On")
Hotstring(":*:apropos", 			func("ViaClipboard").bind("à propos"), "On")
Hotstring(":*:fyi.", 			func("ViaClipboard").bind("For your information"), "On")
Hotstring(":*:asap.", 			func("ViaClipboard").bind("as soon as possible"), "On")
Hotstring(":*:afaik.", 			func("ViaClipboard").bind("as far as I know"), "On")
Hotstring(":*:btw.", 			func("ViaClipboard").bind("by the way"), "On")
Hotstring(":b0*?:email",		func("NormalWay").bind("{Backspace 5}e-mail"), "On")
Hotstring(":*:sharepoint",		func("ViaClipboard").bind("Sharepoint"), "On")
Hotstring(":*:sp.", 			func("ViaClipboard").bind("Sharepoint"), "On")
Hotstring(":B0*:usa", func("NormalWay").bind("{BackSpace 3}USA"), "Off")
Hotstring(":*:USA.", func("ViaClipboard").bind("United States of America"), "Off")
