Hotstring(":B0*:pwm", func("NormalWay").bind("{Backspace 3}PWM"), "On")
Hotstring(":*:PWM.", func("NormalWay").bind("Pulse-Width Modulation"), "On")
Hotstring(":B0*:usa", func("NormalWay").bind("{Backspace 3}USA"), "On")
Hotstring(":*:USA.", func("ViaClipboard").bind("United States of America"), "On")
Hotstring(":*:hsz31", func("NormalWay").bind("HSZ31"), "On")
Hotstring(":B0*:cot", func("NormalWay").bind("{Backspace 3}CoT"), "On")
Hotstring(":*:CoT.", func("NormalWay").bind("Clearance of Track"), "On")
Hotstring(":B0*:led", func("NormalWay").bind("{BackSpace 3}LED"), "On")
Hotstring(":*:LED.", func("NormalWay").bind("Light Emitting Diode"), "On")
Hotstring(":*:orcad", func("NormalWay").bind("OrCAD"), "On")
Hotstring(":B0*:qna", func("NormalWay").bind("{Backspace 3}Q&A"), "On")
Hotstring(":*:qna.", func("ViaClipboard").bind("Questions and Answers"), "On")
Hotstring(":B0*:api", func("NormalWay").bind("{BackSpace 3}API"), "On")
Hotstring(":*:API.", func("ViaClipboard").bind("Application Programming Interface"), "On")
Hotstring("::eg", func("NormalWay").bind("e.g."), "On")
Hotstring("::ie", func("NormalWay").bind("i.e."), "On")
Hotstring(":B0*:sql", func("NormalWay").bind("{BackSpace 3}SQL"), "On")
Hotstring(":*:sql.", func("ViaClipboard").bind("Structured Query Language"), "On")
Hotstring(":B0:ux", func("NormalWay").bind("{Backspace 3}UX"), "On")
Hotstring(":*:ux.", func("ViaClipboard").bind("User Experience"), "On")
Hotstring(":*:cu.", func("ViaClipboard").bind("Competence Unit"), "On")
Hotstring(":*:dlds.", func("NormalWay").bind("Drive, Locking, Detection & Signaling"), "On")
Hotstring(":*:dmt rs.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Rolling Stock"), "Off")
Hotstring(":*:dmti.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Infrastructure"), "On")
Hotstring(":B0*:axc", func("NormalWay").bind("{BackSpace 3}AxC"), "On")
Hotstring(":*:axc.", func("ViaClipboard").bind("Axle Counter"), "On")
Hotstring(":B0*:dlds", func("NormalWay").bind("{BackSpace 4}DLD/S"), "On")
Hotstring(":*:dmtrs.", func("ViaClipboard").bind("Diagnostic and Monitoring Technologies for Rolling Stock"), "On")
Hotstring(":B0*:dmtrs", func("NormalWay").bind("{BackSpace 5}DMT RS"), "On")
Hotstring(":B0*:dmti", func("NormalWay").bind("{BackSpace 4}DMT Infra"), "On")
Hotstring(":*:cfo.", func("NormalWay").bind("Chief Financial Officer"), "On")
Hotstring(":B0*:cfo", func("NormalWay").bind("{BackSpace 3}CFO"), "On")
Hotstring(":B0*:cso", func("NormalWay").bind("{BackSpace 3}CSO"), "On")
Hotstring(":*:cso.", func("NormalWay").bind("Chief Sales Officer"), "On")
Hotstring(":B0*:covid", func("NormalWay").bind("{BackSpace 5}COVID-19"), "On")
Hotstring(":*:covid.", func("ViaClipboard").bind("{BackSpace 3}severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)"), "On")
Hotstring(":*:vvv.", func("ViaClipboard").bind("Vereinigte Österreichische Eisen und Stahlwerke & Österreichisch-Alpine Montangengesellschaft"), "On")
Hotstring(":B0*:ui", func("NormalWay").bind("{BackSpace 2}UI"), "On")
Hotstring(":*:ui.", func("ViaClipboard").bind("User Interface"), "On")
Hotstring(":*:can.", func("ViaClipboard").bind("Controller Area Network"), "On")
Hotstring(":B0*:can`t", 		func("NormalWay").bind("{BackSpace 4}CAN"), "On")
Hotstring(":*:shcl.", func("ViaClipboard").bind("TW-2090-171R-SoftwareandHardwareCompatibilityLog.xlsx"), "On")
Hotstring(":*:tbc.", func("ViaClipboard").bind("to be continued"), "On")
Hotstring(":*:pkb.", 			func("ViaClipboard").bind("Produkt Narodowy Brutto"), "On")
Hotstring(":B0*:pkb", 			func("NormalWay").bind("{Backspace 3}PKB"), "On")
Hotstring(":*:siwz.", 			func("ViaClipboard").bind("Specyfikacja Istotnych Warunków Zamówienia"), "On")
Hotstring(":B0*:siwz", 			func("NormalWay").bind("{BackSpace 4}SIWZ"), "On")
Hotstring(":*:oem.", 			func("ViaClipboard").bind("Original Equipment Manufacturer"), "On")
Hotstring(":B0*:oem", 			func("NormalWay").bind("{BackSpace 3}OEM"), "On")
Hotstring(":*:ems.", 			func("ViaClipboard").bind("Electronics Manufacturing Services"), "On")
Hotstring(":B0*:ems", 			func("NormalWay").bind("{BackSpace 3}EMS"), "On")
Hotstring(":*:pit", 			func("NormalWay").bind("PIT"), "On")
Hotstring(":B0*:html", 			func("NormalWay").bind("{BackSpace 4}HTML"), "On")
Hotstring(":*:qr.", 			func("NormalWay").bind("{BackSpace 5}Quick Response code"), "On")
Hotstring(":B0*:qr", 			func("NormalWay").bind("{BackSpace 2}QR code"), "On")
Hotstring(":*:otagle", 			func("NormalWay").bind("O T A G L E"), "On")
Hotstring(":*:yt", 			func("ViaClipboard").bind("youtube.com"), "On")
Hotstring(":*:an.", 			func("ViaClipboard").bind("Artur Nowak"), "On")
Hotstring(":*:ac`t", 			func("NormalWay").bind("AC"), "On")
Hotstring(":B0*:dc`t", 			func("NormalWay").bind("{BackSpace 3}DC"), "On")
Hotstring(":*:dc.", 			func("ViaClipboard").bind("Direct Current"), "On")
Hotstring(":*:ac.", 			func("ViaClipboard").bind("Alternating Current"), "On")
Hotstring(":*:rms.", 			func("ViaClipboard").bind("Root Mean Square"), "On")
Hotstring(":B0*:rms", 			func("NormalWay").bind("{BackSpace 3}RMS"), "On")
Hotstring(":*:gps.", 			func("ViaClipboard").bind("Global Positioning System"), "On")
Hotstring(":B0*:gps", 			func("NormalWay").bind("{BackSpace 3}GPS"), "On")
Hotstring(":*:pdf.", 			func("ViaClipboard").bind("Portable Document Format"), "On")
Hotstring(":B0*:pdf", 			func("NormalWay").bind("{BackSpace 3}PDF"), "On")
Hotstring(":C1*:gsm.", 			func("ViaClipboard").bind("Global System for Mobile Communications"), "On")
Hotstring(":B0*:gsm", 			func("NormalWay").bind("{BackSpace 3}GSM"), "On")
Hotstring(":*:plm.", 			func("ViaClipboard").bind("Product Lifecycle Management"), "On")
Hotstring(":B0*:plm", 			func("NormalWay").bind("{BackSpace 3}PLM"), "On")
Hotstring(":*:cad.", 			func("ViaClipboard").bind("Computer Aided Design"), "On")
Hotstring(":B0*:cad", 			func("NormalWay").bind("{BackSpace 3}CAD"), "On")
Hotstring(":*0:3d", 			func("NormalWay").bind("3D"), "On")
Hotstring("::2d", 			func("NormalWay").bind("2D"), "On")
Hotstring(":*:wsc.", 			func("ViaClipboard").bind("Wheel Sensor Cable"), "On")
Hotstring(":B0*:wsc", 			func("NormalWay").bind("{BackSpace 3}WSC"), "On")

Hotstring(":*:eq.", 			func("ViaClipboard").bind("Emotional Quotient"), "On")
Hotstring("::eq", 			func("NormalWay").bind("EQ"), "On")
Hotstring(":*:iq.", 			func("ViaClipboard").bind("Inteligence Quotient"), "On")
Hotstring("::iq", 			func("NormalWay").bind("IQ"), "On")
Hotstring(":*:ei.", 			func("ViaClipboard").bind("Emotional Intelligence"), "On")
Hotstring("::ei", 			func("NormalWay").bind("EI"), "On")
Hotstring("::pas2e", 			func("NormalWay").bind("passé"), "On")
Hotstring(":*:dwg.", 			func("NormalWay").bind("Drawing Exchange Format"), "Off")
Hotstring("::dwg", 			func("NormalWay").bind("DWG"), "On")
Hotstring(":*:dxf.", 			func("NormalWay").bind("Drawing Exchange Format"), "On")
Hotstring("::dxf", 			func("NormalWay").bind("DXF"), "On")
Hotstring(":*:flowers.", 			func("NormalWay").bind("💐: 🌹🍀🌻🌺🌸"), "On")
Hotstring(":*T:jooomla", 			func("ViaClipboard").bind("Joomla!"), "On")
