Hotstring(":*:axmpl.", func("ViaClipboard").bind("moduł uniwersalny"), "On")
Hotstring(":*:axmen.",				func("ViaClipboard").bind("universal module"), "On")
Hotstring(":b0*:axm",				func("NormalWay").bind("{BackSpace 3}AXM"), "On")
Hotstring(":*:axmrpl.",			func("ViaClipboard").bind("moduł uniwersalny rozszerzony o wyjścia przekaźnikowe"), "On")
Hotstring(":*:axmren.",			func("ViaClipboard").bind("universal module extended with relay outputs"), "On")
Hotstring(":*:axmr.",				func("NormalWay").bind("AXM^=R^="), "On")
Hotstring(":*:axmiopl.",			func("ViaClipboard").bind("moduł uniwersalny rozszerzony o wejścia i wyjścia binarne"), "On")
Hotstring(":*:axmioen.",			func("ViaClipboard").bind("universal module extended with binary inputs and outputs"), "On")
Hotstring(":*:axmio.",				func("NormalWay").bind("AXM^=IO^="), "On")	
Hotstring(":*:axma",				func("NormalWay").bind("AXM{Space}/{Space}AXM^=R^={Space}/{Space}AXM^=IO^="), "On")
Hotstring(":b0*x:axmp.",			func("NormalWay").bind("{BackSpace 5}AXM,{Space}AXM^=R^=,{Space}AXM^=IO^="), "On")
Hotstring(":*:nout",				func("ViaClipboard").bind("~OUT"), "On")
Hotstring(":*:cok.", func("ViaClipboard").bind("czujnik koła"), "On")
Hotstring(":*b0:cok",				func("NormalWay").bind("{Backspace 3}COK"), "On")
Hotstring(":*:wsu.",				func("ViaClipboard").bind("wheel sensor unit"), "On")
Hotstring(":*b0:wsu",				func("NormalWay").bind("{Backspace 3}WSU"), "On")
Hotstring(":*:ihd1",				func("NormalWay").bind("I^=HD1^="), "On")
Hotstring(":*:ihd2",				func("NormalWay").bind("I^=HD2^="), "On")
Hotstring(":*:hd1en.",				func("ViaClipboard").bind("HD1 (the 1st head of wheel sensor)"), "On")
Hotstring(":*:hd2en.",				func("ViaClipboard").bind("HD2 (the 2nd head of wheel sensor)"), "On")
Hotstring(":*:hd1pl.",				func("ViaClipboard").bind("HD1 (pierwsza głowica czujnika koła)"), "On")
Hotstring(":*:hd2pl.",				func("ViaClipboard").bind("HD2 (druga głowica czujnika koła)"), "On")
Hotstring(":*:uniacpl.",			func("ViaClipboard").bind("(uniwersalny) system liczenia osi"), "On")
Hotstring(":*:uniacen.",			func("ViaClipboard").bind("(universal) axle counting system"), "On")
Hotstring(":b0*:uniac",			func("NormalWay").bind("{BackSpace 5}UniAC"), "On")
Hotstring(":*:uniac2pl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) system liczenia osi drugiej generacji"), "On")
Hotstring(":*:uniac2en.",			func("NormalWay").bind("{BackSpace 2}(universal) axle counting system of 2nd generation"), "On")
Hotstring(":b0*:uniac2",			func("NormalWay").bind("{BackSpace 6}UniAC[2]"), "On")
Hotstring(":*:uniac1pl.",			func("ViaClipboard").bind("(uniwersalny) system liczenia osi pierwszej generacji"), "On")
Hotstring(":*:uniac1en.",			func("ViaClipboard").bind("(universal) axle counting system of 1st generation"), "On")
Hotstring(":b0*:uniac1",			func("NormalWay").bind("{BackSpace 6}UniAC[1]"), "On")
Hotstring(":*:uniacxpl.",			func("NormalWay").bind("{BackSpace 2}rodzina uniwersalnych systemów liczenia osi"), "On")
Hotstring(":*:uniacxen.",			func("NormalWay").bind("{BackSpace 2}family of universal axle counting system"), "On")
Hotstring(":b0*:uniacx",			func("NormalWay").bind("{BackSpace 6}UniAC[x]"), "On")
Hotstring(":*:unias1ppl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) czujnik koła typu UniAS[1{+}]"), "On")
Hotstring(":*:unias1pen.",			func("NormalWay").bind("{BackSpace 2}(universal) UniAS[1{+}] type wheel sensor"), "On")
Hotstring(":b0*:unias1p",			func("NormalWay").bind("{BackSpace 9}UniAS[1{+}]"), "On")
Hotstring(":*:unias2ipl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) czujnik koła typu UniAS[2i]"), "On")
Hotstring(":*:unias2ien.",			func("NormalWay").bind("{BackSpace 2}(universal) UniAS[2i] type wheel sensor"), "On")
Hotstring(":b0*:unias2i",			func("NormalWay").bind("{BackSpace 9}UniAS[2i]"), "Off")
Hotstring(":*:unias1pl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) czujnik koła typu UniAS[1]"), "On")
Hotstring(":*:unias1en.",			func("NormalWay").bind("{BackSpace 2}(universal) UniAS[1] type wheel sensor"), "On")
Hotstring(":b0*:unias1",			func("NormalWay").bind("{BackSpace 6}UniAS[1]"), "On")
Hotstring(":*:unias2pl.",			func("NormalWay").bind("{BackSpace 2}(uniwersalny) czujnik koła typu UniAS[2]"), "On")
Hotstring(":*:unias2en.",			func("NormalWay").bind("{BackSpace 2}(universal) UniAS[2] type wheel sensor"), "On")
Hotstring(":b0*:unias2",			func("NormalWay").bind("{BackSpace 6}UniAS[2]"), "On")
Hotstring(":*:uniasxpl.", 			func("NormalWay").bind("{BackSpace 2}rodzina (uniwersalnych) czujników osi"), "On")
Hotstring(":*:uniasxen.", 			func("NormalWay").bind("{BackSpace 2}(universal) wheel sensor family"), "On")
Hotstring(":b0*:uniasx",			func("NormalWay").bind("{BackSpace 6}UniAS[x]"), "On")		
Hotstring(":*:uniaspl.",			func("ViaClipboard").bind("(uniwersalny) czujnik koła"), "On")
Hotstring(":*:uniasen.",			func("ViaClipboard").bind("(universal) wheel sensor"), "On")
Hotstring(":b0*:unias",			func("NormalWay").bind("{BackSpace 5}UniAS"), "On")
Hotstring(":*:unircpl.",			func("ViaClipboard").bind("(uniwersalny) uchwyt czujnika koła"), "On")
Hotstring(":*:unircen.",			func("ViaClipboard").bind("(universal) wheel sensor rail clamp"), "On")
Hotstring(":*b0:unirc",			func("NormalWay").bind("{Backspace 5}UniRC"), "On")
Hotstring(":*:azcpl.",				func("ViaClipboard").bind("moduł ochrony przeciwprzepięciowej dedykowany dla rodziny czujników osi UniAS[x]"), "On")
Hotstring(":*:azcen.",				func("ViaClipboard").bind("surge protection module dedicated for UniAS[x] wheel sensor family"), "On")
Hotstring(":*b0:azc",				func("NormalWay").bind("{Backspace 3}AZC"), "On")
Hotstring(":*:magpl.",				func("ViaClipboard").bind("magistrala"), "On")
Hotstring(":*:magen.",				func("ViaClipboard").bind("backplane"), "On")
Hotstring(":b0*:mag",				func("NormalWay").bind("{Backspace 3}MAG"), "On")
Hotstring(":b0*:magsacpl.",			func("NormalWay").bind("{BackSpace 37}zintegrowany moduł diagnostyczny, komunikacyjny i zasilający"), "On")
Hotstring(":b0*:magsacen.",			func("NormalWay").bind("{BackSpace 37}integrated diagnostic, communication and voltage supply module"), "On")
Hotstring(":*:header.",			func("ViaClipboard").bind("integrated diagnostic, communication and voltage supply module"), "On")
Hotstring(":B0*:magsac", func("NormalWay").bind("{Backspace 6}MAG_SAC (MAG_SUP + MAG_ADM + MAG_COM)"), "On")
Hotstring(":B0*:magsak", func("NormalWay").bind("{Backspace 6}MAG_SAC (MAG_SUP + MAG_ADM + MAG_COM)"), "On")
Hotstring(":*:magsuppl.",			func("NormalWay").bind("{Backspace 1}moduł zasilający"), "On")
Hotstring(":*:magsupen.",			func("NormalWay").bind("{Backspace 1}voltage supply module"), "On")
Hotstring(":*b0:magsup",			func("NormalWay").bind("{Backspace 6}MAG_SUP"), "On")
Hotstring(":*:magadmen.",			func("NormalWay").bind("{Backspace 1}basic diagnostic module"), "On")
Hotstring(":*:magadmpl.",			func("NormalWay").bind("{Backspace 1}moduł podstawowej diagnostyki"), "On")
Hotstring(":*b0:magadm",			func("NormalWay").bind("{Backspace 6}MAG_ADM"), "On")
Hotstring(":*:admpl.",				func("ViaClipboard").bind("moduł rozszerzonej diagnostyki"), "On")
Hotstring(":*:admen.",				func("ViaClipboard").bind("extended diagnostics module"), "On")
Hotstring(":*b0:adm",				func("NormalWay").bind("{Backspace 3}ADM"), "On")
Hotstring(":*:mrupl.",				func("ViaClipboard").bind("moduł rozszerzonej diagnostyki"), "On")
Hotstring(":*:mruen.",				func("ViaClipboard").bind("module rack unit"), "On")
Hotstring(":*b0:mru",				func("NormalWay").bind("{Backspace 3}MRU"), "On")
Hotstring(":*:asmpl.",				func("ViaClipboard").bind("moduł oceniający"), "On")
Hotstring(":*:asmen.",				func("ViaClipboard").bind("evaluation module"), "On")
Hotstring(":*b0:asm",				func("NormalWay").bind("{Backspace 3}ASM"), "On")
Hotstring(":*:acmpl.",				func("ViaClipboard").bind("moduł liczący"), "On")
Hotstring(":*:acmen.",				func("ViaClipboard").bind("counting module"), "On")
Hotstring(":*b0:acm",				func("NormalWay").bind("{Backspace 3}ACM"), "On")
Hotstring(":*:aimpl.",				func("ViaClipboard").bind("moduł wejść wyjść"), "On")
Hotstring(":*:aimen.",				func("ViaClipboard").bind("inputs and outputs module"), "On")
Hotstring(":*b0:aim",				func("NormalWay").bind("{Backspace 3}AIM"), "On")
Hotstring(":*:abmpl.",				func("ViaClipboard").bind("kaseta"), "On")
Hotstring(":*:abmen.", func("ViaClipboard").bind("enclosure"), "On")
Hotstring(":*b0:abm",				func("NormalWay").bind("{Backspace 3}ABM"), "On")
Hotstring(":*:anszuapl.",			func("ViaClipboard").bind("system zarządzania usługami"), "On")
Hotstring(":*b0:anszua",			func("NormalWay").bind("{Backspace 6}AnSzuA"), "On")
Hotstring(":*:uniblpl.",			func("ViaClipboard").bind("system (uniwersalnej) blokady liniowej"), "On")
Hotstring(":*:uniblen.",			func("ViaClipboard").bind("UniBL"), "On")
Hotstring(":*b0:unibl",			func("NormalWay").bind("{Backspace 5}UniBL"), "On")
Hotstring(":*:dsat.",				func("ViaClipboard").bind("detekcja Stanów awaryjnych Taboru"), "On")
Hotstring(":*b0:dsat",				func("NormalWay").bind("{Backspace 4}dSAT"), "On")
Hotstring(":*:asdek.",				func("ViaClipboard").bind("automatyczny system detekcji i eksploatacji kół pojazdów kolejowych"), "On")
Hotstring(":*b0:asdek",			func("NormalWay").bind("{Backspace 5}ASDEK"), "On")
Hotstring(":*:s2d.",				func("ViaClipboard").bind("szlakowy system diagnostyki"), "On")
Hotstring(":*b0:s2d",				func("NormalWay").bind("{Backspace 3}SSD"), "On")
Hotstring(":*:gotcha",				func("ViaClipboard").bind("GOTCHA"), "On")
Hotstring(":*:phoenix",			func("ViaClipboard").bind("PHOENIX"), "On")
Hotstring(":*b0:pm",				func("NormalWay").bind("{Backspace 2}PM"), "On")
Hotstring(":*:dp.",				func("ViaClipboard").bind("Dział Produkcji i Zaopatrzenia"), "On")
Hotstring(":B0*:dp", func("NormalWay").bind("{Backspace 2}DPiZ"), "Off")
Hotstring(":*:dpiz.",				func("ViaClipboard").bind("Dział Produkcji i Zaopatrzenia"), "On")
Hotstring(":*b0:dpiz",				func("NormalWay").bind("{Backspace 4}DPiZ"), "On")
Hotstring(":*:du.",				func("ViaClipboard").bind("Dział Usług i Realizacji"), "On")
Hotstring(":B0*:du", func("NormalWay").bind("{Backspace 2}DUiR"), "Off")
Hotstring(":*:duir.",				func("ViaClipboard").bind("Dział Usług i Realizacji"), "On")
Hotstring(":*b0:duir",				func("NormalWay").bind("{Backspace 4}DUiR"), "On")
Hotstring(":*:dr.",				func("ViaClipboard").bind("Dział Rozwoju"), "On")
Hotstring(":B0*:dr", func("NormalWay").bind("{Backspace 2}DR"), "Off")
Hotstring(":*:wim.",				func("ViaClipboard").bind("Weighing in Motion"), "On")
Hotstring(":*b0:wim",				func("NormalWay").bind("{Backspace 3}WIM"), "On")
Hotstring(":*:wdd.",				func("ViaClipboard").bind("Wheel Defect Detection"), "On")
Hotstring(":*b0:wdd",				func("NormalWay").bind("{Backspace 3}WDD"), "On")
Hotstring(":*:hbd.",				func("ViaClipboard").bind("Hot-Box Detector"), "On")
Hotstring(":*b0:hbd",				func("NormalWay").bind("{Backspace 3}HBD"), "On")
Hotstring(":*:hwd.",				func("ViaClipboard").bind("Hot-Wheel Detector"), "On")
Hotstring(":*b0:hwd",				func("NormalWay").bind("{Backspace 3}HWD"), "On")
Hotstring(":*:mb.",				func("ViaClipboard").bind("Multi Beam"), "On")
Hotstring(":*b0:mb",				func("NormalWay").bind("{Backspace 2}MB"), "On")
Hotstring(":*:mds.",				func("ViaClipboard").bind("modular Diagnostic System"), "On")
Hotstring(":*b0:mds",				func("NormalWay").bind("{Backspace 3}MDS"), "On")
Hotstring(":B0*:vo", func("NormalWay").bind("estalpine"), "Off")
Hotstring(":*b0:voe",				func("NormalWay").bind("{Backspace 9}stalpine Signaling Poland"), "On")
Hotstring(":b0:voes",				func("NormalWay").bind("{Backspace 2} Sp. z o.o."), "On")
Hotstring(":B0*:voesi", func("NormalWay").bind("{Backspace 8}Siershahn"), "On")
Hotstring(":*:si.",				func("ViaClipboard").bind("Siershahn"), "On")
Hotstring(":*:so.",				func("ViaClipboard").bind("Sopot"), "On")
Hotstring(":*:sai.",				func("ViaClipboard").bind("Sainerholz"), "On")
Hotstring(":*:nipv.",				func("ViaClipboard").bind("584-025-39-29"), "On")
Hotstring(":*:adres.",				func("ViaClipboard").bind("Jana z Kolna 26c, 81-859 Sopot, Polska"), "On")
Hotstring(":*:addres2.",			func("ViaClipboard").bind("Jana z Kolna 26c, 81-859 Sopot, Poland"), "On")
Hotstring(":*:hpir.",				func("ViaClipboard").bind("Hardware Prototype Implementation Report"), "On")
Hotstring(":*b0:hpir",				func("NormalWay").bind("{Backspace 4}HPIR"), "On")
Hotstring(":*:rnd.",				func("ViaClipboard").bind("Research & Development"), "On")
Hotstring(":*b0:rnd",				func("NormalWay").bind("{Backspace 3}R&D"), "On")
Hotstring(":*b0:cps",				func("NormalWay").bind("{Backspace 3}Cooperation Platform Sopot (https://solidsystemteamwork.voestalpine.root.local/internalprojects/vaSupp/CPS/SitePages/Home.aspx)"), "On")
Hotstring(":*:muk",				func("ViaClipboard").bind("MDS Upgrade Kit (https://solidsystemteamwork.voestalpine.root.local/Processes/custprojects/780MDSUpgradeKit/SitePages/Home.aspx)"), "On")
Hotstring(":*b0:sps",				func("NormalWay").bind("{Backspace 3}Documentation Sharepoint Sopot"" (https://team.voestalpine.net/site/4077/default.aspx)"), "On")
Hotstring(":*:bbt.",				func("ViaClipboard").bind("Bearing and Brake Temperature"), "On")
Hotstring(":*b0:bbt",				func("NormalWay").bind("{Backspace 3}BBT"), "On")
Hotstring(":B0*:unirc", func("NormalWay").bind("{BackSpace 5}UniRC"), "On")
Hotstring(":*:subrack 6", func("ViaClipboard").bind("Subrack 6"), "On")
Hotstring(":*:subrack 14", func("ViaClipboard").bind("Subrack 14"), "On")
Hotstring(":*:subrack 15", func("ViaClipboard").bind("Subrack 15"), "On")
Hotstring(":B0*:du ", func("NormalWay").bind("{Backspace 3}DUiR "), "On")
Hotstring(":B0*:dr ", func("NormalWay").bind("{Backspace 3}DR "), "On")
Hotstring(":*:FP52en.", func("ViaClipboard").bind("shape gauge with simulation side"), "On")
Hotstring(":*:FP52pl.", func("ViaClipboard").bind("przymiar z symulatorem koła"), "On")
Hotstring(":*:SG52en.", func("ViaClipboard").bind("shape gauge"), "On")
Hotstring(":*:SG52pl.", func("ViaClipboard").bind("przymiar"), "On")

Hotstring(":B0*:vo.", func("NormalWay").bind("{BackSpace}estalpine"), "On")
